### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci-archive/geojsonlint#22]
(or new maintainer _team_)

This package was archived on GitHub but not on CRAN.
If someone has interest in maintaining it, it won't be archived on CRAN.
We'd transfer it back to the ropensci GitHub organization.

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci-archive/admin

**Comment by maelle** [comment]
https://github.com/ropensci/MODIStsp/pull/263

**Comment by maelle** [comment]
https://github.com/ropensci/geojson/issues/44

**Comment by maelle** [comment]
I'll leave the call in this month's newsletter but will remove it after that, so if no one volunteers we'll have to archive geojsonlint.

**Comment by maelle** [comment]
https://github.com/ropensci/geojsonio/issues/201

**Comment by maelle** [comment]
https://github.com/ranghetti/sen2r/issues/454

**Comment by maelle** [comment]
@sckott no rev dep any more https://cran.r-project.org/web/packages/geojsonlint/index.html, would you be able to require the archival to CRAN? Thank you :pray:

**Comment by sckott** [comment]
yes, i will ask them to archive the pkg

**Comment by maelle** [comment]
thank you!

**Comment by maelle** [comment]
thanks again!
